.headers on
.mode csv
.output BIOCHEM.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM BIOCHEM) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'BIOCHEM';
.output AEROSCI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM AEROSCI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'AEROSCI';
.output HLTHPOL.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM HLTHPOL) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'HLTHPOL';
.output MILITSCI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM MILITSCI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'MILITSCI';
.output NEUROBIO.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM NEUROBIO) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'NEUROBIO';
.output AAAS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM AAAS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'AAAS';
.output AADS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM AADS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'AADS';
.output AMES.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM AMES) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'AMES';
.output ARABIC.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ARABIC) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ARABIC';
.output ARTHIST.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ARTHIST) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ARTHIST';
.output ARTSSCI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ARTSSCI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ARTSSCI';
.output ARTSVIS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ARTSVIS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ARTSVIS';
.output BIOLOGY.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM BIOLOGY) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'BIOLOGY';
.output BME.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM BME) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'BME';
.output BRAINSOC.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM BRAINSOC) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'BRAINSOC';
.output CEE.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CEE) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CEE';
.output CELLBIO.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CELLBIO) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CELLBIO';
.output CESC.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CESC) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CESC';
.output CHEM.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CHEM) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CHEM';
.output CHILDPOL.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CHILDPOL) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CHILDPOL';
.output CHINESE.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CHINESE) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CHINESE';
.output CINE.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CINE) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CINE';
.output CLST.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CLST) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CLST';
.output CMAC.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CMAC) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CMAC';
.output COMPSCI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM COMPSCI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'COMPSCI';
.output CREOLE.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CREOLE) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CREOLE';
.output CULANTH.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM CULANTH) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'CULANTH';
.output DANCE.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM DANCE) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'DANCE';
.output DECSCI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM DECSCI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'DECSCI';
.output DOCST.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM DOCST) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'DOCST';
.output ECE.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ECE) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ECE';
.output ECON.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ECON) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ECON';
.output ECS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ECS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ECS';
.output EDUC.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM EDUC) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'EDUC';
.output EGR.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM EGR) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'EGR';
.output EHD.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM EHD) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'EHD';
.output ENERGY.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ENERGY) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ENERGY';
.output ENGLISH.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ENGLISH) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ENGLISH';
.output ENRGYEGR.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ENRGYEGR) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ENRGYEGR';
.output EOS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM EOS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'EOS';
.output ENVIRON.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ENVIRON) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ENVIRON';
.output ETHICS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ETHICS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ETHICS';
.output EVANTH.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM EVANTH) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'EVANTH';
.output FRENCH.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM FRENCH) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'FRENCH';
.output GERMAN.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM GERMAN) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'GERMAN';
.output GLHLTH.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM GLHLTH) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'GLHLTH';
.output GREEK.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM GREEK) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'GREEK';
.output GSF.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM GSF) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'GSF';
.output HEBREW.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM HEBREW) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'HEBREW';
.output HINDI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM HINDI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'HINDI';
.output HISTORY.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM HISTORY) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'HISTORY';
.output HUMANDEV.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM HUMANDEV) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'HUMANDEV';
.output IE.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM IE) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'IE';
.output IMMUNOL.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM IMMUNOL) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'IMMUNOL';
.output Internatl.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM Internatl) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'Internatl';
.output ISS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ISS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ISS';
.output JEWISHST.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM JEWISHST) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'JEWISHST';
.output ITALIAN.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ITALIAN) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ITALIAN';
.output JPN.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM JPN) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'JPN';
.output KICHE.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM KICHE) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'KICHE';
.output KOREAN.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM KOREAN) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'KOREAN';
.output LATAMER.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM LATAMER) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'LATAMER';
.output LATIN.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM LATIN) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'LATIN';
.output LINGUIST.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM LINGUIST) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'LINGUIST';
.output LIT.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM LIT) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'LIT';
.output LSGS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM LSGS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'LSGS';
.output MARSCI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM MARSCI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'MARSCI';
.output MATH.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM MATH) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'MATH';
.output Mech.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM Mech) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'Mech';
.output MEDREN.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM MEDREN) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'MEDREN';
.output MGM.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM MGM) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'MGM';
.output MMS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM MMS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'MMS';
.output MUSIC.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM MUSIC) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'MUSIC';
.output NAVALSCI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM NAVALSCI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'NAVALSCI';
.output NEUROSCI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM NEUROSCI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'NEUROSCI';
.output PATHOL.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM PATHOL) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'PATHOL';
.output PERSIAN.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM PERSIAN) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'PERSIAN';
.output PHARM.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM PHARM) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'PHARM';
.output PHIL.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM PHIL) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'PHIL';
.output PHYSEDU.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM PHYSEDU) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'PHYSEDU';
.output PHYSICS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM PHYSICS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'PHYSICS';
.output PJMS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM PJMS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'PJMS';
.output POE.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM POE) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'POE';
.output POLISH.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM POLISH) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'POLISH';
.output POLSCI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM POLSCI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'POLSCI';
.output PORTUGUE.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM PORTUGUE) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'PORTUGUE';
.output PSY.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM PSY) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'PSY';
.output PUBPOL.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM PUBPOL) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'PUBPOL';
.output RELIGION.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM RELIGION) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'RELIGION';
.output RIGHTS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM RIGHTS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'RIGHTS';
.output ROMST.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM ROMST) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'ROMST';
.output RUSSIAN.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM RUSSIAN) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'RUSSIAN';
.output SCISOC.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM SCISOC) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'SCISOC';
.output SES.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM SES) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'SES';
.output SOCIOL.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM SOCIOL) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'SOCIOL';
.output SPANISH.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM SPANISH) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'SPANISH';
.output STA.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM STA) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'STA';
.output SUSTAIN.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM SUSTAIN) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'SUSTAIN';
.output SWAHILI.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM SWAHILI) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'SWAHILI';
.output SXL.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM SXL) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'SXL';
.output THEATRST.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM THEATRST) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'THEATRST';
.output TURKISH.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM TURKISH) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'TURKISH';
.output VMS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM VMS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'VMS';
.output WRITING.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM WRITING) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'WRITING';
.output HOUSECS.csv
WITH details(course_num, open_seats, total_seats, reserves, percentage, time_recorded) AS (SELECT * FROM HOUSECS) SELECT details.course_num, dept, catalog_num, course_name, topic, section_type, section_num,open_seats, total_seats, reserves, percentage, time_recorded FROM details, sections, names WHERE names.course_num = details.course_num AND sections.course_num = details.course_num AND dept = 'HOUSECS';
